export interface Settings {
  reader_slider: boolean
  reader_optimize: boolean
  reader_fullscreen: boolean
  grid_size: number
  webtoon_zoom: boolean
  downloads_wifi: boolean
  webtoon_gaps: boolean
  tracker_enabled: boolean
  tips_closed: string[]
  zoom_mode: string
  reader_background: string
  nav_main: string
  local_storage: string
  tracker_freq: string
  nav_labels: boolean
  sources_new: boolean
  reader_mode: string
  reader_mode_detect: boolean
  backup_periodic: boolean
  pages_tab: boolean
  nav_pinned: boolean
  images_proxy_2: string
  reading_indicators: boolean
  reader_taps_ltr: boolean
  reverse_chapters: boolean
  pages_dir_ask: boolean
  exit_confirm: boolean
  tracker_wifi: boolean
  sources_sort_order: string
  sources_version: number
  logging: boolean
  details_last_tab: number
  doh: string
  images_proxy: boolean
  reading_time: boolean
  screenshots_policy: string
  details_tab: string
  list_mode_2: string
  no_nsfw: boolean
  grid_view_chapters: boolean
  reader_bar: boolean
  search_suggest_types: string[]
  theme: string
  updates_unstable: boolean
  prefetch_content: string
  stats_on: boolean
  reader_zoom_buttons: boolean
  local_manga_dirs: string[]
  mirror_switching: boolean
  chapters_clear_auto: boolean
  track_sources: string[]
  reader_switchers: string[]
  color_theme: string
  amoled_theme: boolean
  enhanced_colors: boolean
  backup_periodic_output: string
  downloads_format: string
  related_manga: boolean
  reader_animation2: string
  dynamic_shortcuts: boolean
  backup_periodic_freq: string
  app_locale: string
  reader_screen_on: boolean
  reader_volume_buttons: boolean
  suggestions: boolean
  pages_preload: string
  sources_grid: boolean
  pages_numbers: boolean
  proxy_type: string
}
